import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from SignalDecorator import signal


class DCWidth:
    """
    Donchian Channel Width – a volatility indicator based on the range
    of the Donchian Channel (high-low over `period` bars).

    The width is expressed as a percentage of the current close to make it
    comparable across instruments and timeframes.

    Regime signals (continuous, 0/1) are generated by comparing the width
    against static or dynamic thresholds (identical threshold logic to
    GarmanKlass, BBWidth, etc.).

    Parameters
    ----------
    data : pd.DataFrame
        Must contain 'High', 'Low', 'Close' columns.
    period : int, default 20
        Lookback period for the Donchian Channel.
    threshold_high, threshold_low : float or None
        Static absolute thresholds for high/low width (in % of price).
        Use with caution – these depend on the instrument and timeframe.
    threshold : float or None, optional
        Legacy single threshold – sets both high and low to the same value.
    dynamic_threshold : str, default 'percentile'
        Method for dynamic thresholds: 'percentile', 'std', or 'mean'.
    percentile_high, percentile_low : int, default 70, 30
        Percentile values for the high/low thresholds when using 'percentile'.
    std_mult_high, std_mult_low : float, default 1.0, 1.0
        Standard‑deviation multipliers for 'std' method.
    long_window : int, default 252
        Rolling window length for dynamic threshold calculation.
    """

    def __init__(self, data, period=20,
                 threshold_high=None, threshold_low=None,
                 threshold=None,
                 dynamic_threshold='percentile',
                 percentile_high=70, percentile_low=30,
                 std_mult_high=1.0, std_mult_low=1.0,
                 long_window=5000):
        self.data = data
        self.period = period
        self.long_window = long_window
        self.dw_width = self._compute()
        self.category = "volatility"

        # Threshold setup – identical to GarmanKlass / BBWidth
        if threshold_high is not None or threshold_low is not None:
            self.threshold_high = threshold_high
            self.threshold_low = threshold_low
            self.threshold_type = 'static_dual'
        elif threshold is not None:
            self.threshold_high = threshold
            self.threshold_low = threshold
            self.threshold_type = 'static'
        else:
            self.threshold_type = dynamic_threshold
            self.percentile_high = percentile_high
            self.percentile_low = percentile_low
            self.std_mult_high = std_mult_high
            self.std_mult_low = std_mult_low
            self._update_dynamic_threshold()

    def _compute(self):
        """Compute Donchian Channel width as a percentage of the closing price."""
        upper = self.data['High'].rolling(window=self.period).max()
        lower = self.data['Low'].rolling(window=self.period).min()
        # Width in price units, then normalise to % of close
        width = (upper - lower) / self.data['Close'] * 100.0
        return width

    def _update_dynamic_threshold(self):
        """Compute rolling dynamic thresholds (high & low) for the width series."""
        if self.threshold_type == 'percentile':
            self.dynamic_high = self.dw_width.rolling(self.long_window).quantile(
                self.percentile_high / 100.0)
            self.dynamic_low  = self.dw_width.rolling(self.long_window).quantile(
                self.percentile_low / 100.0)
        elif self.threshold_type == 'std':
            rolling_mean = self.dw_width.rolling(self.long_window).mean()
            rolling_std  = self.dw_width.rolling(self.long_window).std()
            self.dynamic_high = rolling_mean + self.std_mult_high * rolling_std
            self.dynamic_low  = rolling_mean - self.std_mult_low * rolling_std
        elif self.threshold_type == 'mean':
            self.dynamic_high = self.dw_width.rolling(self.long_window).mean()
            self.dynamic_low  = self.dynamic_high   # fallback, only one threshold
        else:
            raise ValueError("Invalid dynamic_threshold")

    # ---------- Regime signals (continuous, int8) ----------
    @signal(direction="both", signal_type="continuous", weight=1.0)
    def high_volatility_regime(self):
        """Return 1 when width > high threshold, else 0."""
        if self.threshold_type in ('static_dual', 'static'):
            thr = self.threshold_high
        else:
            thr = self.dynamic_high
        return pd.Series(
            np.where(self.dw_width > thr, 1, 0),
            index=self.dw_width.index,
            dtype=np.int8
        )

    @signal(direction="both", signal_type="continuous", weight=1.0)
    def low_volatility_regime(self):
        """Return 1 when width < low threshold, else 0."""
        if self.threshold_type in ('static_dual', 'static'):
            thr = self.threshold_low
        else:
            thr = self.dynamic_low
        return pd.Series(
            np.where(self.dw_width < thr, 1, 0),
            index=self.dw_width.index,
            dtype=np.int8
        )

    @signal(direction="both", signal_type="continuous", weight=1.0)
    def medium_volatility_regime(self):
        """Return 1 when width between low and high thresholds (inclusive), else 0."""
        if self.threshold_type in ('static_dual', 'static'):
            high = self.threshold_high
            low  = self.threshold_low
        else:
            high = self.dynamic_high
            low  = self.dynamic_low
        return pd.Series(
            np.where((self.dw_width >= low) & (self.dw_width <= high), 1, 0),
            index=self.dw_width.index,
            dtype=np.int8
        )

    # ---------- Plot ----------
    def plot(self, start_idx=None, end_idx=None):
        """Interactive Plotly chart with Donchian width, thresholds, and regime markers."""
        if start_idx is None:
            start_idx = 0
        if end_idx is None:
            end_idx = len(self.data)

        df_plot = self.data.iloc[start_idx:end_idx]
        width_plot = self.dw_width.iloc[start_idx:end_idx]

        # Thresholds
        if self.threshold_type in ('static_dual', 'static'):
            high_thr = pd.Series(self.threshold_high, index=width_plot.index)
            low_thr  = pd.Series(self.threshold_low, index=width_plot.index)
        else:
            high_thr = self.dynamic_high.iloc[start_idx:end_idx]
            low_thr  = self.dynamic_low.iloc[start_idx:end_idx]

        # Signals (sliced Series)
        high_sig = self.high_volatility_regime().iloc[start_idx:end_idx]
        low_sig  = self.low_volatility_regime().iloc[start_idx:end_idx]

        # Datetime indices for markers
        idx_high = high_sig[high_sig == 1].index
        idx_low  = low_sig[low_sig == 1].index

        fig = make_subplots(
            rows=2, cols=1, shared_xaxes=True,
            vertical_spacing=0.05, row_heights=[0.6, 0.4],
            subplot_titles=('Price & Volatility Regimes', f'Donchian Width ({self.period})')
        )

        # Candlestick
        fig.add_trace(go.Candlestick(
            x=df_plot.index,
            open=df_plot['Open'], high=df_plot['High'],
            low=df_plot['Low'], close=df_plot['Close'],
            name='Price'
        ), row=1, col=1)

        # High volatility markers
        fig.add_trace(go.Scatter(
            x=idx_high,
            y=df_plot.loc[idx_high, 'Close'],
            mode='markers',
            marker=dict(color='orange', size=9, symbol='triangle-up'),
            name='High Volatility'
        ), row=1, col=1)

        # Low volatility markers
        fig.add_trace(go.Scatter(
            x=idx_low,
            y=df_plot.loc[idx_low, 'Close'],
            mode='markers',
            marker=dict(color='green', size=7, symbol='circle'),
            name='Low Volatility'
        ), row=1, col=1)

        # Width line – coloured by regime
        colors = []
        for i in range(len(width_plot)):
            w = width_plot.iloc[i]
            if w > high_thr.iloc[i]:
                colors.append('red')
            elif w < low_thr.iloc[i]:
                colors.append('green')
            else:
                colors.append('orange')

        for i in range(1, len(width_plot)):
            fig.add_trace(go.Scatter(
                x=width_plot.index[i-1:i+1],
                y=width_plot.iloc[i-1:i+1],
                mode='lines',
                line=dict(color=colors[i-1], width=2),
                showlegend=False
            ), row=2, col=1)

        # Dummy legend trace for the width line
        fig.add_trace(go.Scatter(
            x=[width_plot.index[0]], y=[width_plot.iloc[0]],
            mode='lines', line=dict(color='darkgray', width=2),
            name='Donchian Width'
        ), row=2, col=1)

        # Threshold lines
        fig.add_trace(go.Scatter(
            x=high_thr.index, y=high_thr.values,
            mode='lines', line=dict(color='red', dash='dash', width=1),
            name='High Threshold'
        ), row=2, col=1)
        fig.add_trace(go.Scatter(
            x=low_thr.index, y=low_thr.values,
            mode='lines', line=dict(color='green', dash='dot', width=1),
            name='Low Threshold'
        ), row=2, col=1)

        fig.update_layout(
            title='Donchian Channel Width – Volatility Regimes',
            xaxis_title='Date', yaxis_title='Price',
            height=800, width=1000, template='plotly_dark',
            hovermode='x unified',
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
        )
        fig.update_yaxes(title_text="Width (% of Close)", row=2, col=1)
        fig.update_xaxes(rangeslider_visible=False)
        fig.show()