import pandas as pd
import numpy as np
from numba import njit
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from SignalDecorator import signal


# ----------------------------------------------------------------------
# Numba implementation of the Ehlers Roofing Filter
# ----------------------------------------------------------------------
@njit(cache=True)
def _ehlers_roofing_filter(price, hp_period=10, smooth_period=48):
    """
    Ehlers Roofing Filter – isolates high‑frequency noise from price.

    1. High‑pass filter with correct alpha (Ehlers' 2‑pole HP).
    2. SuperSmoother low‑pass filter with correct input coefficient.
    """
    n = len(price)
    hp = np.zeros(n)
    ss = np.zeros(n)

    if n < 3:
        return ss

    # ---------- Correct High‑Pass filter alpha ----------
    angle    = 0.707 * 2.0 * np.pi / hp_period
    cos_a    = np.cos(angle)
    sin_a    = np.sin(angle)
    alpha_hp = (cos_a + sin_a - 1.0) / cos_a

    hp[0] = 0.0
    hp[1] = 0.0

    for i in range(2, n):
        hp[i] = ((1.0 - alpha_hp / 2.0) ** 2 * (price[i] - 2.0 * price[i - 1] + price[i - 2])
                 + 2.0 * (1.0 - alpha_hp) * hp[i - 1]
                 - (1.0 - alpha_hp) ** 2 * hp[i - 2])

    # ---------- Correct SuperSmoother coefficients ----------
    pi = np.pi
    a1 = np.exp(-np.sqrt(2.0) * pi / smooth_period)
    b1 = 2.0 * a1 * np.cos(np.sqrt(2.0) * pi / smooth_period)
    a1_sq = a1 * a1
    c1 = 1.0 - b1 + a1_sq    # correct input weight (Ehlers calls it c1)

    # Initialise SuperSmoother
    ss[0] = hp[0]
    if n > 1:
        ss[1] = hp[1]

    for i in range(2, n):
        ss[i] = (c1 * (hp[i] + hp[i - 1]) / 2.0
                 + b1 * ss[i - 1]
                 - a1_sq * ss[i - 2])

    return ss


class ERFilt:
    """
    Ehlers Roofing Filter – volatility based on high‑frequency noise.

    The Roofing Filter isolates the high‑frequency component of price,
    capturing market noise. The absolute value of this filtered series,
    smoothed over a short window, serves as a measure of instantaneous
    volatility. High values indicate elevated noise / volatility.

    Regime signals (continuous 0/1) are generated by comparing the
    smoothed noise against static or dynamic thresholds, following the
    same logic as GarmanKlass, BBWidth, and DonchianWidth.

    Parameters
    ----------
    data : pd.DataFrame
        Must contain 'High', 'Low', 'Close'. (Median price H/L used by default.)
    hp_period : int, default 10
        High‑pass filter period (isolates cycles shorter than this).
    smooth_period : int, default 48
        SuperSmoother period (further isolates high‑frequency noise).
    vol_window : int, default 20
        Rolling window for smoothing the absolute filtered values.
    threshold_high, threshold_low : float or None
        Static absolute thresholds for high/low noise level.
    dynamic_threshold : str, default 'percentile'
        'percentile', 'std', or 'mean'.
    percentile_high, percentile_low : int, default 70, 30
    std_mult_high, std_mult_low : float, default 1.0, 1.0
    long_window : int, default 252
        Rolling window for dynamic threshold calculation.
    """

    def __init__(self, data, hp_period=10, smooth_period=48, vol_window=20,
                 threshold_high=None, threshold_low=None,
                 threshold=None,
                 dynamic_threshold='percentile',
                 percentile_high=70, percentile_low=30,
                 std_mult_high=1.0, std_mult_low=1.0,
                 long_window=2000):
        self.data = data
        self.hp_period = hp_period
        self.smooth_period = smooth_period
        self.vol_window = vol_window
        self.long_window = long_window

        # Compute the noise series and its smoothed amplitude
        self.noise_series, self.noise_vol = self._compute()
        self.category = "volatility"

        # Threshold logic – identical to the other volatility indicators
        if threshold_high is not None or threshold_low is not None:
            self.threshold_high = threshold_high
            self.threshold_low = threshold_low
            self.threshold_type = 'static_dual'
        elif threshold is not None:
            self.threshold_high = threshold
            self.threshold_low = threshold
            self.threshold_type = 'static'
        else:
            self.threshold_type = dynamic_threshold
            self.percentile_high = percentile_high
            self.percentile_low = percentile_low
            self.std_mult_high = std_mult_high
            self.std_mult_low = std_mult_low
            self._update_dynamic_threshold()

    def _compute(self):
        """Compute roofing filter output and smoothed volatility."""
        median = (self.data['High'].values + self.data['Low'].values) / 2.0
        filtered = _ehlers_roofing_filter(median, self.hp_period, self.smooth_period)

        # Absolute value smoothed over vol_window – simple EMA for efficiency
        abs_filtered = np.abs(filtered)
        # Use an EMA with a span equal to vol_window
        noise_vol = pd.Series(abs_filtered, index=self.data.index).ewm(
            span=self.vol_window, adjust=False).mean()

        noise_series = pd.Series(filtered, index=self.data.index, name='RoofingFilter')
        noise_vol.name = 'NoiseVolatility'
        return noise_series, noise_vol

    def _update_dynamic_threshold(self):
        """Compute rolling dynamic thresholds on the noise volatility series."""
        if self.threshold_type == 'percentile':
            self.dynamic_high = self.noise_vol.rolling(self.long_window).quantile(
                self.percentile_high / 100.0)
            self.dynamic_low = self.noise_vol.rolling(self.long_window).quantile(
                self.percentile_low / 100.0)
        elif self.threshold_type == 'std':
            rolling_mean = self.noise_vol.rolling(self.long_window).mean()
            rolling_std = self.noise_vol.rolling(self.long_window).std()
            self.dynamic_high = rolling_mean + self.std_mult_high * rolling_std
            self.dynamic_low = rolling_mean - self.std_mult_low * rolling_std
        elif self.threshold_type == 'mean':
            self.dynamic_high = self.noise_vol.rolling(self.long_window).mean()
            self.dynamic_low = self.dynamic_high   # fallback
        else:
            raise ValueError("Invalid dynamic_threshold")

    # ---------- Continuous regime signals ----------
    @signal(direction="both", signal_type="continuous", weight=1.0)
    def high_volatility_regime(self):
        """Return 1 when noise volatility > high threshold, else 0."""
        if self.threshold_type in ('static_dual', 'static'):
            thr = self.threshold_high
        else:
            thr = self.dynamic_high
        return pd.Series(
            np.where(self.noise_vol > thr, 1, 0),
            index=self.noise_vol.index,
            dtype=np.int8
        )

    @signal(direction="both", signal_type="continuous", weight=1.0)
    def low_volatility_regime(self):
        """Return 1 when noise volatility < low threshold, else 0."""
        if self.threshold_type in ('static_dual', 'static'):
            thr = self.threshold_low
        else:
            thr = self.dynamic_low
        return pd.Series(
            np.where(self.noise_vol < thr, 1, 0),
            index=self.noise_vol.index,
            dtype=np.int8
        )

    @signal(direction="both", signal_type="continuous", weight=1.0)
    def medium_volatility_regime(self):
        """Return 1 when noise volatility between low and high thresholds (inclusive)."""
        if self.threshold_type in ('static_dual', 'static'):
            high = self.threshold_high
            low = self.threshold_low
        else:
            high = self.dynamic_high
            low = self.dynamic_low
        return pd.Series(
            np.where((self.noise_vol >= low) & (self.noise_vol <= high), 1, 0),
            index=self.noise_vol.index,
            dtype=np.int8
        )

    # ---------- Plot ----------
    def plot(self, start_idx=None, end_idx=None):
        if start_idx is None:
            start_idx = 0
        if end_idx is None:
            end_idx = len(self.data)

        df_plot = self.data.iloc[start_idx:end_idx]
        vol_plot = self.noise_vol.iloc[start_idx:end_idx]
        filt_plot = self.noise_series.iloc[start_idx:end_idx]

        # Thresholds
        if self.threshold_type in ('static_dual', 'static'):
            high_thr = pd.Series(self.threshold_high, index=vol_plot.index)
            low_thr = pd.Series(self.threshold_low, index=vol_plot.index)
        else:
            high_thr = self.dynamic_high.iloc[start_idx:end_idx]
            low_thr = self.dynamic_low.iloc[start_idx:end_idx]

        # Signals
        high_sig = self.high_volatility_regime().iloc[start_idx:end_idx]
        low_sig = self.low_volatility_regime().iloc[start_idx:end_idx]
        idx_high = high_sig[high_sig == 1].index
        idx_low = low_sig[low_sig == 1].index

        fig = make_subplots(
            rows=3, cols=1, shared_xaxes=True,
            vertical_spacing=0.04,
            row_heights=[0.5, 0.25, 0.25],
            subplot_titles=('Price & Regimes', 'Roofing Filter (Noise)', 'Noise Volatility')
        )

        # Row 1: Candlestick + regime markers
        fig.add_trace(go.Candlestick(
            x=df_plot.index,
            open=df_plot['Open'], high=df_plot['High'],
            low=df_plot['Low'], close=df_plot['Close'],
            name='Price'
        ), row=1, col=1)

        fig.add_trace(go.Scatter(
            x=idx_high, y=df_plot.loc[idx_high, 'Close'],
            mode='markers', marker=dict(color='orange', size=9, symbol='triangle-up'),
            name='High Noise (Vol)'
        ), row=1, col=1)

        fig.add_trace(go.Scatter(
            x=idx_low, y=df_plot.loc[idx_low, 'Close'],
            mode='markers', marker=dict(color='green', size=7, symbol='circle'),
            name='Low Noise (Vol)'
        ), row=1, col=1)

        # Row 2: Roofing filter output (zero‑centered noise)
        fig.add_trace(go.Scatter(
            x=filt_plot.index, y=filt_plot,
            mode='lines', line=dict(color='cyan', width=1.5),
            name='Roofing Filter'
        ), row=2, col=1)
        fig.add_hline(y=0, line_dash="dot", line_color="gray", row=2, col=1)

        # Row 3: Smoothed absolute noise (volatility) with thresholds
        colors = []
        for i in range(len(vol_plot)):
            v = vol_plot.iloc[i]
            if v > high_thr.iloc[i]:
                colors.append('red')
            elif v < low_thr.iloc[i]:
                colors.append('green')
            else:
                colors.append('orange')

        for i in range(1, len(vol_plot)):
            fig.add_trace(go.Scatter(
                x=vol_plot.index[i-1:i+1],
                y=vol_plot.iloc[i-1:i+1],
                mode='lines', line=dict(color=colors[i-1], width=2),
                showlegend=False
            ), row=3, col=1)

        fig.add_trace(go.Scatter(
            x=[vol_plot.index[0]], y=[vol_plot.iloc[0]],
            mode='lines', line=dict(color='darkgray', width=2),
            name='Noise Volatility'
        ), row=3, col=1)

        fig.add_trace(go.Scatter(
            x=high_thr.index, y=high_thr.values,
            mode='lines', line=dict(color='red', dash='dash', width=1),
            name='High Threshold'
        ), row=3, col=1)
        fig.add_trace(go.Scatter(
            x=low_thr.index, y=low_thr.values,
            mode='lines', line=dict(color='green', dash='dot', width=1),
            name='Low Threshold'
        ), row=3, col=1)

        fig.update_layout(
            title=f'Ehlers Roofing Filter Volatility (HP={self.hp_period}, SS={self.smooth_period})',
            xaxis_title='Date', yaxis_title='Price',
            height=900, width=1000, template='plotly_dark',
            hovermode='x unified',
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
        )
        fig.update_yaxes(title_text="Filter", row=2, col=1)
        fig.update_yaxes(title_text="Noise Vol", row=3, col=1)
        fig.update_xaxes(rangeslider_visible=False)
        fig.show()